main: com.minegusta.mgracesredone.main.Main
author: janie177
name: MGRacesRedone
version: ${project.version}
depend: [WorldGuard]
commands:
   race:
      aliases: [races, class, classes, rc]
      usage: /Race
      description: All information you need about races.
   raceadmin:
      aliases: [ra, raceowner, usetheprindl]
      usage: /RaceAdmin
      description: Admin commands for races. Don't you abuse those Lucas I swear.
   perkreset:
      usage: /perkreset
      description: Resets your perks WITHOUT refunding you.
   perk:
      aliases: [perks, power, powers, pp, skilltree, tree, ]
      usage: /Race
      description: All information you need about races.