main: com.minegusta.mgracesredone.main.Main
author: janie177
name: MGRacesRedone
version: ${project.version}
softdepend: [WorldGuard]
commands:
   race:
      aliases: [races, class, classes, ra, rc]
      usage: /Race
      description: All information you need about races.